### ISSUE TITLE
Compile error in android studio

### ISSUE THREAD

**Issue by Jxliew** [STMicroelectronics/STNFCSensor_Android#1]
Was not able to run application successfully in android studio and had several java issues.
![Capture](https://user-images.githubusercontent.com/54020919/62852814-6f73c680-bce2-11e9-981c-be8965402a8e.PNG)

**Comment by GiovanniVisentiniST** [comment]
Hi

you are running a dummy test not the application.
I fix it with the test with commit 22c047b1b6fe8b683503e7f64890ccff08fb9502

witch kind of java issue did you found?

Best Regards
Giovanni

**Comment by Jxliew** [comment]
Hi 

Sorry I am relatively new to development of android applications. I was assuming that once the source code had been downloaded from github, I should able to run the dummy test on android studio. Please correct me if I am wrong.

Best Regards,
Jia

**Comment by GiovanniVisentiniST** [comment]
no no your approach was excellent!

Giovanni

**Comment by Jxliew** [comment]
I had undertaken the following steps: 

1. Downloaded the source code via github (picture attached)
2. Run the dummy test via an android emulator provided by android studio

However, after running the dummy test the android application crashes in the emulator.

Thanks for the advice,
Jia 

![Capture](https://user-images.githubusercontent.com/54020919/62859089-157bfc80-bcf4-11e9-92c0-ff08fab20829.PNG)

**Comment by GiovanniVisentiniST** [comment]
do you have any error on the log cat?

could be because the emulator doesn't emulate NFC.. and the app require the nfc.

**Comment by Jxliew** [comment]
Yes that might be a problem. Is there way to either emulate the NFC or disable the requirements for NFC?

Jia

**Comment by GiovanniVisentiniST** [comment]
Well the app show the data read from the nfc, so it is a requirement.

About the emulator seems that NFC is not supported: https://stackoverflow.com/questions/49146532/nfc-tag-emulation-for-android-virtual-device-avd

Best Regards
Giovanni

**Comment by Jxliew** [comment]
Thanks for the advice! I will consider either side loading the dummy test to an android phone or faking a NFC tag scan on android studio.

Have a great day,
Jia
